Repository faker-ruby/faker-bot, pull requests merged in 2019-07, with the labels that each got.

#28 chore: Rename from FakerBot to Faker::CLI
  Gemfile
  Gemfile.lock
  bin/console
  bin/faker
  faker-cli.gemspec
  lib/faker-cli.rb
  lib/faker/cli.rb
  lib/faker/cli/command.rb
  lib/faker/cli/commands/list.rb
  lib/faker/cli/commands/search.rb
  lib/faker/cli/reflector.rb
  lib/faker/cli/reflectors/list.rb
  lib/faker/cli/reflectors/search.rb
  lib/faker/cli/renderer.rb
  lib/faker/cli/version.rb
  lib/faker/renderer.rb
  lib/fakerbot.rb
  lib/fakerbot/cli.rb
  lib/fakerbot/command.rb
  lib/fakerbot/commands/list.rb
  lib/fakerbot/commands/search.rb
  lib/fakerbot/reflector.rb
  lib/fakerbot/reflectors/list.rb
  lib/fakerbot/reflectors/search.rb
  lib/fakerbot/templates/list/.gitkeep
  lib/fakerbot/version.rb
  spec/faker/cli/commands/list_spec.rb
  spec/faker/cli/commands/search_spec.rb
  spec/faker/cli/reflectors/list_spec.rb
  spec/faker/cli/reflectors/search_spec.rb
  spec/faker/cli/renderer_spec.rb
  spec/integration/list_spec.rb
  spec/integration/search_spec.rb
  spec/spec_helper.rb
Labels: chores

#29 Update README to republish faker-cli
  README.md
Labels: documentation

#31 Gem name should be faker-bot
  Gemfile.lock
  Guardfile
  README.md
  bin/console
  bin/faker
  faker-bot.gemspec
  faker-cli-0.4.5.gem
  lib/faker-bot.rb
  lib/faker/bot.rb
  lib/faker/bot/command.rb
  lib/faker/bot/commands/list.rb
  lib/faker/bot/commands/search.rb
  lib/faker/bot/reflector.rb
  lib/faker/bot/reflectors/list.rb
  lib/faker/bot/reflectors/search.rb
  lib/faker/bot/renderer.rb
  lib/faker/bot/version.rb
  lib/faker/renderer.rb
  spec/faker/bot/commands/list_spec.rb
  spec/faker/bot/commands/search_spec.rb
  spec/faker/bot/reflectors/list_spec.rb
  spec/faker/bot/reflectors/search_spec.rb
  spec/faker/bot/renderer_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#32 Chore: CleanUp
  Guardfile
  lib/faker/renderer.rb
Labels: chores

#33 Skip Faker Deprecation Warnings; The CLI handles that - II
  lib/faker/bot.rb
  lib/faker/bot/reflector.rb
Labels: bug

#34 Add CI & QA Badges
  README.md
Labels: chores
